# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line, check build.gradle files instead.

# Gradle memory settings
org.gradle.jvmargs=-Xmx2048m

# Parallel build
org.gradle.parallel=true

# Enable on-demand configuration
org.gradle.configureondemand=false

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Kotlin
kotlin.code.style=official
